# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'resolvers',
  sources = globs('*.py'),
  dependencies = [
    'contrib/node/src/python/pants/contrib/node/subsystems/resolvers',
    'contrib/webpack/src/python/pants/contrib/webpack/targets',
  ],
)
