# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'targets',
  sources = globs('*.py'),
  dependencies = [
    'src/python/pants/util:memo',
    'src/python/pants/base:exceptions',
    'contrib/node/src/python/pants/contrib/node/subsystems/resolvers',
  ],
)
